### PR TITLE
bug: keeping information on page change

### LINKED ISSUE #203: All changes in input fields lost when you switch to another page
**Describe the bug**
Any inserted data or change that you made in Method, URL and .. will be lost  when you switch to another page

**To Reproduce**
1. Change URL input value to something like `https://jsonplaceholder.typicode.com`
2. Go to another page, for example, Click on 'Settings' (gear icon on the top-right corner)
3. Go back to the HTTP page again
4. see the URL input, it's value turn back to default `https://reqres.in`

This happens for all other changes 

**Expected behavior**
When we go to another page the changes should remain

### PR DESCRIPTION
**Pull request by breno-pereira**
Work done to address issue #203
( Closes #203 )

### Changes
- Create state file
- Create mutation file
- Use `VuexPersist` to save the state in `localStorage`
- Remove local data from `index.vue`

### CODE REVIEW

**Comment by liyasthomas** [comment]
@breno-pereira there's is a little merge conflict. Please rebase and pull or solve conflict manually.

**Comment by liyasthomas** [comment]
CI tests passed 🙌🏼
Will run some manual tests and then merge!

**Comment by liyasthomas** [comment]
@breno-pereira 
Using `VuexPersist ` for preserving state seems to be working fine 🎉

The only bug I found is: on `POST`, `PUT` & `PATCH` requests, the payload is not being send. I went through the code and found payload is being sent as `string` instead `JSON`

Before (postwoman.io):
Screen Shot 2019-10-25 at 8 17 57 AM

After (#211)
Screen Shot 2019-10-25 at 8 18 20 AM

**Comment by NBTX** [comment]
Closes #203

**Comment by liyasthomas** [comment]
I again went through the code and now I doubt encoding payload as query parameters were already there 😕

**Comment by breno-pereira** [comment]
@liyasthomas 
Now I think it's correct

**Pull request merged**
