### PR TITLE
Add basic e2e tests

### PR DESCRIPTION
**Pull request by yubathom**
## Add basic e2e tests with cypress
Related to #65.

preview of `npm run dev:e2e`

postwoman_basic-e2e

this should be running in ci too - https://travis-ci.org/yubathom/postwoman/builds/593324131
at `before_scripts`

Screenshot_2019-10-03 Build #138 - yubathom postwoman - Travis CI

wich should give some reports at every pull requests
Screenshot_2019-10-03 Build #138 - yubathom postwoman - Travis CI(1)

## New scripts: 
* `npm run tests` - run tests once in cli mode. Now just these e2e. In future we should run unit tests too.  
* `npm run dev:e2e`- will start localhos:3000 and run e2e tests within cypress app browser. This is the default mode to tdd. 

## Notes:
- I'm not mounting and testing the docker container. Just testing the dev server (`run dev`) mounted at the travis-ci. 
- Though would be a better approach (running on docker) the dev server is the same enviroment that is deploying the front end. So I think this should be enough right now.
- [Cypress](https://www.cypress.io/) is awesome and we can add fake backend responses to run tests (see  `tests/e2e/fixtures/` and `tests/e2e/support/commands.js`). We should create some fixtures of firebase. Something like [this](https://github.com/prescottprue/cypress-firebase).
- We should write more tests. Any ideas?

### CODE REVIEW

**Comment by liyasthomas** [comment]
This is AWESOME ✨

We'll write more tests 👌

**Comment by liyasthomas** [comment]
Tiny suggestions for clean code
https://www.deepcode.ai/app/gh/liyasthomas/postwoman/3ad814ebb71019ca1e9707e4338bacda1af7c0ad/liyasthomas/postwoman/ade7733d4751402cb46def4b4c3cf293b02706bf/_/%2Ftests%2Fe2e%2Fintegration%2Ffeature.url-queries.spec.js/javascript%2Fdc%2FPROMISE_NOT_CATCHED_GENERAL/code/

**Comment by liyasthomas** [comment]
@NBTX seems to be busy for review. @yubathom can merge this on your requirements.

After merge, we could add more tests.

**Comment by yubathom** [comment]
> Tiny suggestions for clean code
> https://www.deepcode.ai/app/gh/liyasthomas/postwoman/3ad814ebb71019ca1e9707e4338bacda1af7c0ad/liyasthomas/postwoman/ade7733d4751402cb46def4b4c3cf293b02706bf/_/%2Ftests%2Fe2e%2Fintegration%2Ffeature.url-queries.spec.js/javascript%2Fdc%2FPROMISE_NOT_CATCHED_GENERAL/code/

Hey @liyasthomas, thank you for reviewing and merging. And sorry co's I've got sick and was out theese days. 

I tested the deepcodecheck changes and that broke the tests. I think is because I am not able to catch in [cypress promises](https://github.com/cypress-io/cypress/issues/5094). 

I will check at cypress docs and look for workarounds to keep the tests code cleaner in future tests.

**Comment by yubathom** [comment]
And just deleted at travis the envs `SURGE_LOGIN`and `SURGE_TOKEN`.

Those were required to already closed #151 and #148.

**Pull request merged**
