### PR TITLE
Add proxy auto-detection.

### PR DESCRIPTION
**Pull request by NBTX**
image

image

This obviously includes changes to the `lang` strings.

---

The proxy auto-detection is shown under the following criteria:
1. the user is running the postwoman-proxy application locally, and has installed the SSL certificates,
2. the user is not already using a functioning proxy server.

### CODE REVIEW

**Comment by AndrewBastin** [comment]
@NBTX I was thinking we just need show a small toast notification with an action at first to show that we have detected the proxy server.

But other than that, this seems awesome.

**Comment by liyasthomas** [comment]
@NBTX what's the status of this PR?

**Comment by NBTX** [comment]
@liyasthomas Apologies, I got caught up. I should have this finished by this weekend.

**Comment by liyasthomas** [comment]
@NBTX this PR is getting outdated. Let's merge this first as per our initial plans and iterate over it in the upcoming days?

**Comment by NBTX** [comment]
@liyasthomas Okay, I'll make a note to catch up on it!

**Comment by AndrewBastin** [comment]
Umm, this has been idle for a while ?

**Comment by liyasthomas** [comment]
Yep. Will close this temporarily. @NBTX feel free to reopen.

**Pull request closed without merging**
