### PR TITLE
feat: semistandard linting

### PR DESCRIPTION
**Pull request by mdt2**
Work done to address issue #98 

## Description of work

* Add semistandard package for linting
* Use semistandard's `semistandard --fix` feature to fix some of the existing linting errors

## To test
Pull down the branch and run `npm run lint` to see semistandard in action

### CODE REVIEW

**Comment by mdt2** [comment]
Good call, @liyasthomas. I'm also getting linting failures in `/assets/js/pwa.js` for `localStorage` being undefined, as well as `/functions/index.js` for never using `functions`. Should those be added to the ignore list too?

**Comment by liyasthomas** [comment]
@mdt2 well, ignoring all will make linting irrelevant isn't it? I should've consider linting at the beginning of the project. My bad.

Let's do one thing now, ignore all files causing build failure and pull again.

**Comment by liyasthomas** [comment]
a09d7d76d3a41fc9504e8768f224423ae9360276 resolves this, hence closing.

**Comment by liyasthomas** [comment]
a09d7d76d3a41fc9504e8768f224423ae9360276 resolves this, hence closing.

**Pull request closed without merging**
