### PR TITLE
Added regex to handle url parts

### LINKED ISSUE #62: Fast URL entry
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Similar to Postman's interface, I think we should make the URL entry a single bar at the top, with the method on the left. Then we should just parse the URL and fill in the relevant information.

We could keep the extra sections but this would make Postwoman a lot more intuitive and faster to use.

**Describe alternatives you've considered**
n/a

**Additional context**
image
*As shown, Postman parses the URL as it is entered and automatically fills in the relevant sections.*

### LINKED ISSUE #581: Bigger URL and/or Path input field
I'm working on a project and I'm dealing with similar URLs of an API.
Postwoman only provides a small input field to add in the URL

image

I cannot properly see what URL I'm sending the request to.

Even the history section shows a small excerpt of the entire URL.

### Possible Solution

This is what postman does when thrown a big URL

image

### PR DESCRIPTION
**Pull request by JacobAnavisca**
Fix #62 
Fix #581

### CODE REVIEW

**Comment by liyasthomas** [comment]
@JacobAnavisca there seems to be a problem with parsing URL while passing `URL` via parameter. That's why tests are failing. I suggest you to run `npm run dev:e2e` for testing few use cases.

**Comment by liyasthomas** [comment]
@JacobAnavisca pre-commit hooks have been introduced hence please rebase to current master and pull latest change, then send PR.

**Comment by NBTX** [comment]
I don't think we should be using regex for this. JavaScript has a very mature URL API:
https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by JacobAnavisca** [comment]
main reason I'm using regex is to handle environment variables, like <<baseUrl>>/get

**Comment by NBTX** [comment]
Could we substitute them before we try parsing?

**Comment by JacobAnavisca** [comment]
How about regex as a fallback? like so:
`    uri: {
      get() {
        return this.$store.state.request.uri ?
          this.$store.state.request.uri
          : this.url + this.path;
      },
      set(value) {
        this.$store.commit("setState", { value, attribute: "uri" })
        let url;
        if (this.preRequestScript && this.showPreRequestScript) {
          const environmentVariables = getEnvironmentVariablesFromScript(this.preRequestScript);
          url = parseTemplateString(value, environmentVariables);
        }
        try {
          url = new URL(url);
          this.url = url.origin;
          this.path = url.pathname;
        } catch(error) {
          console.log(error)
          let uriRegex = value.match(
            /^((http[s]?:\/\/)?(<<[^\/]+>>)?[^\/]*|)(\/?.*)$/
          );
          this.url = uriRegex[1];
          this.path = uriRegex[4];
        }
      }
    }`

**Pull request merged**
