### PR TITLE
Adding french language basic

### PR DESCRIPTION
**Pull request by thomasbnt**
Hello again ! (#354)  Just adding french language basic to prepare the ground.

- [x] Added `lang/fr-FR.js`
- [x] Modified `nuxt.config.js`

### CODE REVIEW

**Comment by thomasbnt** [comment]
No problem for ping me, I will add the words in French without any problems ! :+1:

**Comment by liyasthomas** [comment]
@thomasbnt new keywords are up! Looking forward on commiting translations ASAP.

Checklist:

- [ ] **Pull the latest changes from `i18n` branch**
- [ ] Find `lang/<<your_file>>.js`
- [ ] **Replace existing dummy translations** with actual translated lacale (no need to update `nuxt.config.js` since language is already added once)
- [ ] Save changes, Commit changes, **Push to `i18n` branch only**

Refer English translation file https://github.com/liyasthomas/postwoman/blob/i18n/lang/en-US.js for reference and stylings. Ping me for any doubts.

**Comment by thomasbnt** [comment]
@liyasthomas already checked by @LaurentBrieu (https://github.com/liyasthomas/postwoman/pull/364)

**Comment by liyasthomas** [comment]
We, then it was a mistake. Nevermind. 😊

**Pull request merged**
