### PR TITLE
Added Turkish language support

### PR DESCRIPTION
**Pull request by AliAnilKocak**
Added lang/tr-TR.js
Modified nuxt.config.js

### CODE REVIEW

**Comment by liyasthomas** [comment]
@AliAnilKocak did you just re-based to `master` branch and pulled change from it?

**Comment by AliAnilKocak** [comment]
Yes, I did only re-based to master

**Comment by liyasthomas** [comment]
i18n branch is kept separate from mater for tracking translations. Would you mind re-base to `i18n` branch and PR again?

**Comment by AliAnilKocak** [comment]
Thanks for the information. I did

**Pull request closed without merging**
