### PR TITLE
Sync path and parameters

### PR DESCRIPTION
**Pull request by hosseinnedaee**
I used _url_ and _querystring_ node.js built-in modules to parse the path and query.

### CODE REVIEW

**Comment by liyasthomas** [comment]
@hosseinnedaee Import cURL seems to be broken. Can you take a look at that

**Comment by hosseinnedaee** [comment]
> @hosseinnedaee Import cURL seems to be broken. While importing cURL generated from Postwoman itself, `path` is not updated. Default path value is persisted even after cURL import. Can you take a look at that. **Locally it works fine by the way confused**
> To reproduce:
> 
> 1. goto postwoman.io
> 2. send a `POST` request
> 3. copy `cURL` code
> 4. again visit postwoman.io
> 5. import cURL
> 6. see `path` is as same as default placeholder, not updated after cURL import

@liyasthomas  anyway, when I import curl it just shows me this error: "cURL is not formatted properly"
Screenshot from 2019-09-30 22-42-31

**Comment by liyasthomas** [comment]
See, on this screenshot `path` field is appended to `URL` as well as to the path field itself. Guess how did that happen?

**Comment by hosseinnedaee** [comment]
Maybe we should wait until fast URL entry #62 to be closed and then I work around it. because I think they depend on each other and maybe after using just one field for `URL` and `Path` the issue be solved. what do you think?

**Pull request merged**
