### PR TITLE
Auto deploy testing branches, test and report

### PR DESCRIPTION
**Pull request by yubathom**
This is related to #65.

### Features
* Add a setup for local e2e tests with [cypress](https://www.cypress.io/).
* Deploy, with travis-ci, the last commit at branches named `tests-*` at [surge.sh](https://surge.sh/). 
* Run tests in this url.
* Send from travis a comment with a brief result report of the tests at the commit page. [See an example at my fork](https://github.com/yubathom/postwoman/commit/612cd491179d9e2612ad0e49bf4b3d20e6d69553#commitcomment-35121756).

Screenshot_2019-09-16 Testing pull request auto-deployment and test report by yubathom · Pull Request #36 · yubathom postwo

### New scripts: 
* `npm run e2e` - run tests locally (already running) `localhost:3000` (cli mode).
* `npm run e2e:open`- run tests locally to (already running) `localhost:3000` in browser mode
* `npm run dev:e2e` - start `localhost:3000` and tests (browser mode). This is the default command to tdd.

### obs:
- The deployment pattern of urls at surge is: `http://postwoman-:commithash.surge.sh`
- I added my surge user data at travis (login and token). It would be better to replace it for @liyasthomas account (to keep things centralized).
- The github token env at travis should be able to write comment issues with curl (probably it is already).
- I tried to do this routine at Pull Requests but [I failed](https://github.com/liyasthomas/postwoman/pull/148). I think it would be better. But could not find a workaround to [pull requests restrictions](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).

### CODE REVIEW

**Comment by liyasthomas** [comment]
@yubathom What are the required env tokens..?

**Comment by yubathom** [comment]
To run the tests in public urls and check the changes ourselves and discuss it in  common url at PR's. In `testdeploy.sh`  is required __SURGE_LOGIN__ and __SURGE_TOKEN__.
The github token are needed to send the report messages.

Would you prefer to keep the tests runs just locally? That won't require any of theese envs..

**Comment by yubathom** [comment]
To create the to token need to install surge globally :
```bash
npm i -g surge
# create an account and run 
surge token
```

**Comment by liyasthomas** [comment]
I think tests on CI is important too. Let me work on this and will will let you know.

**Comment by yubathom** [comment]
Ok

**Comment by liyasthomas** [comment]
@NBTX @AndrewBastin test when you're free

**Comment by yubathom** [comment]
Since a docker image (#164 / #165)  is available I guess that'd be better to run these tests with `docker componse` at ci . Need to update this.

**Comment by NBTX** [comment]
In that case, I'll test when you accomodate #164 / #165

**Comment by yubathom** [comment]
Revisited this and I think this got unnecessarily complicated. I will create another PR with simpler setup and more tests.

**Pull request closed without merging**
