### PR TITLE
Code highlighting

### PR DESCRIPTION
**Pull request by JacobAnavisca**
Probably needs some updating. A bit of a hack with some of the CSS.

### CODE REVIEW

**Comment by liyasthomas** [comment]
I stumbled upon a bug in which repeated requests response body are not updated in textarea.

To reproduce:
0. Send a request
1. Send another request
2. Response body is not updated
3. Preview HTML is also kinda broken

**Comment by JacobAnavisca** [comment]
@liyasthomas Sorry for merging! I thought the OK meant good to merge. Do you have an API that returns HTML so I can test and get a fix in?

**Comment by liyasthomas** [comment]
All 404 returns HTML response.

**Comment by JacobAnavisca** [comment]
@liyasthomas Just committed a fix for the response issue. I didn't notice an issue with the Preview HTML unless I'm missing something.

**Comment by liyasthomas** [comment]
@JacobAnavisca Thanks for the quick response

**Pull request merged**
