### PR TITLE
Terranblake/basic environment

### PR DESCRIPTION
**Pull request by liyasthomas**

### CODE REVIEW

**Comment by NBTX** [comment]
Why is this stale? What is this waiting on?

**Comment by liyasthomas** [comment]
Its incomplete, and far behind us. I don't think it'll be able to catch up or solve latest bindings and all.

**Comment by NBTX** [comment]
I vote we close this and look at reimplementing.

**Comment by liyasthomas** [comment]
Terran went off-grid. Will close it.

**Pull request closed without merging**
