### PR TITLE
Link multiple auth providers

### PR DESCRIPTION
**Pull request by liyasthomas**
This is the hacky solution- Open alternate signin popup on error catch.
 - [x] Google
 - [x] GitHub
 - [ ] Combine login flow in `login.vue` and `settings.vue` page.

### CODE REVIEW

**Comment by dmitryyankowski** [comment]
How do I test this commit using the Netlify preview build link? @liyasthomas I press login with Google/Github and a box pops up, and then closes. Should I do it on localhost? Is Firebase Auth setup to allow logins from Localhost?

**Comment by liyasthomas** [comment]
only production and localhost work with Firebase Auth

**Comment by dmitryyankowski** [comment]
> only production and localhost work with Firebase Auth

Gotcha! Will take a look :)

**Comment by dmitryyankowski** [comment]
@liyasthomas not sure how it was working on your local computer 😄 But I fixed a few scoping issues, and issues with toast notifications. If you notice.. on the live site, if you login; there's no toast that say's "Logged out" (When there should be). However; I fixed that. 

This PR should fix any issues I saw.

**Note**: I didn't look too far into how i18n works in this project, and if a key is missing in one of the lang JS files.. will it fallback to a key in the EN file? That's the only thing I'm wondering, but didn't look into. If there are isssues with users from other countries not seeing toast boxes.. that could be a root cause.

@liyasthomas

**Pull request merged**
