### PR TITLE
Add hal+json as a supported media type option

### PR DESCRIPTION
**Pull request by davidyscott**
Add `application/hal+json` as a Content-Type option to the dropdown for requests, treating the actual request body identically to `application/json`.  See #88

### CODE REVIEW

**Comment by liyasthomas** [comment]
Please provide a description to PR for testing purposes

**Comment by liyasthomas** [comment]
Can you please mention at least one mock/test API which has `application/hal+json` response? This is to run few tests so that I could verify and merge this PR into `master`.

**Comment by liyasthomas** [comment]
Rebase and pull again

**Comment by davidyscott** [comment]
With apologies, I may not have time to get back to this for several days.  If someone else is able to step in, go ahead.  Otherwise, I haven't forgotten!

**Comment by liyasthomas** [comment]
#129 solved this, hence closing.

**Pull request closed without merging**
