### PR TITLE
Fix proxy URL

### PR DESCRIPTION
**Pull request by NBTX**

### CODE REVIEW

**Comment by NBTX** [comment]
Merging immediately because this broke production.

**Comment by NBTX** [comment]
...or not?

**Comment by liyasthomas** [comment]
Im running

**Comment by liyasthomas** [comment]
https://travis-ci.com/liyasthomas/postwoman/builds

**Comment by NBTX** [comment]
Ah yeah I figured out what was going on. The link sent me to travis-ci.org which for some reason is completely seperate to travis-ci.com and didn't even recognize that my account existed.

**Comment by liyasthomas** [comment]
Btw, you can't hot merge PRs without CI finishing tests and builds. New commit (even a merge) trigger concurrent build. This caused build error. On travis-ci.com (not .org) build was already triggered. 

I wonder why this damn Travis CI bot haven't migrated to .com yet 🤐

**Comment by NBTX** [comment]
Yeah or at the very least they should check if you're logged in on one and not the other and redirect you 🙄

**Pull request merged**
