### PR TITLE
Fix .all-contributorsrc badge template.

### PR DESCRIPTION
**Pull request by NBTX**
This changes the badge template from Markdown to HTML which will mean it is rendered as our README header is in HTML and Markdown that is nested in HTML does not render.

### CODE REVIEW

**Comment by liyasthomas** [comment]
Heyy! Its good, btw can we make it next to the current badges.. It just default to the first line of readme 😕

**Comment by NBTX** [comment]
Yeah I'll take a look, there's probably some template comment.

**Comment by liyasthomas** [comment]
@NBTX got it: 

Also note that it needs to find the following tags in order to update the badge:
```
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
<!-- ALL-CONTRIBUTORS-BADGE:END -->
```

this fixes that.

**Comment by NBTX** [comment]
Okay placing the badge on the page is terribly documented for some reason but I'm led to believe that if I revert to the markdown template and put the markdown badge on the page in the desired location, it should detect the badge in that location the next time it needs to be updated and replace it.

**Comment by liyasthomas** [comment]
Yeah badge will work

**Comment by NBTX** [comment]
Okay, let's try merging this one when the CI completes then.

**Comment by liyasthomas** [comment]
lets run bot.
@all-contributors please add @NBTX for code

**Comment by liyasthomas** [comment]
@all-contributors please add @NBTX for design

**Comment by liyasthomas** [comment]
Guess badge issue is fixed

**Comment by liyasthomas** [comment]
@all-contributors please add @jamesgeorge007 for code

**Comment by liyasthomas** [comment]
Badge working as expected

**Pull request merged**
