### PR TITLE
🎨 Add theme support (and settings storage)

### PR DESCRIPTION
**Pull request by NBTX**
image

image

image

This PR adds support for background theme selection and accent color selection. Additional background/accent colors can be easily defined the application. (Refer to `/layouts/settings.vue` for guidance.)

Here's a full list of what this PR achieves:
- Move root (var) style properties to `/assets/css/themes.scss`
- Improve mobile navigation
- Create section component for the collapsable sections.
- Create logo component, so color can be changed.

- Add settings page
- Add option to select theme color
- Add option to select theme background
- Add option to enable/disable multi-colored frames.

- Add settings to VueX Store
- Persist VueX store in LocalStorage.

This PR also:
- solves https://github.com/liyasthomas/postwoman/issues/32
- solves https://github.com/liyasthomas/postwoman/pull/18 with regard to the Nuxt refactor.

### CODE REVIEW

**Comment by NBTX** [comment]
As with the other PRs, you can try out the changes on my GitHub Pages instance:
https://nbtx.github.io/postwoman-vue/

**Comment by NBTX** [comment]
Okay

**Comment by NBTX** [comment]
Rebased and merged.

**Comment by liyasthomas** [comment]
@NBTX Send button on HTTP tabs isn't working.

**Comment by liyasthomas** [comment]
Found what's causing the error #58

**Pull request merged**
