### PR TITLE
Feature/post request tests

### LINKED ISSUE #465: [suggestion] - Tests tab
**Is your feature request related to a problem? Please describe.**

I really love postwoman, and I'm using it to test my rest api. Problem: I currently can't make a serie of tests. I'm searching a way to automate requests and check if everything is fine or not, like if x request returns me correctly y response.

Of course maybe it's already implemented, and in this case I didn't find the way to do that, sorry about that.

**Describe the solution you'd like**

Add a new tab named "tests" where we could add a requests we saved in our collections, and a "predictable" reponse. Postwoman could test requests automatically using 1 single button.

**Describe alternatives you've considered**

Using the documentation tab, and implement it directly inside this one.

**Additional context**

/

### PR DESCRIPTION
**Pull request by nickpalenchar**
Closes #465 

Want to get this in while it's still in sync with master. Minimal but functional and ready to be used 😄 

The tests button is next to the pre-request script button, which opens a window to code tests. A commented out line given an example of a (failing) test. Comment it in to test the test. Other examples are documented [here](https://github.com/liyasthomas/postwoman/wiki/Post-Requests-Tests), and can all be tried.

Biggest todo still is saving to history. Will do later this weekend.

The UI is minimal and... a little funky.. could def use some formatting help by someone better at styling than I am!

In terms of functionality+docs I'll add a bit more incrementally once merged. This was a really fun one!
If someone else merges I recommend squashing and merging.. I made a lot of incremental commits.

### CODE REVIEW

**Comment by liyasthomas** [comment]
Failing build seems to be an issue with Travis CI. Will report back after a retry.

**Comment by liyasthomas** [comment]
Let me investigate whats wrong.

**Comment by nickpalenchar** [comment]
thanks

**Comment by liyasthomas** [comment]
There's no problem with our code, while running tests locally everything seem to be working fine. The issue is with Travis CI.

Netlify successfully built the project for deploy preview. Will wait until CI team fixes this issue from their side. Meanwhile I'll optimize the UI a bit.

**Comment by AndrewBastin** [comment]
Actually @nickpalenchar, there is a build issue with your code, I will commit fixes for them in a second.

**Comment by nickpalenchar** [comment]
@AndrewBastin thanks so much for your help!

**Pull request merged**
