### PR TITLE
⌨️Add autocomplete widget with command line completion

### LINKED ISSUE #88: Add support for "application/hal+json" Content-Type
**Is your feature request related to a problem? Please describe.**
Working with a HATEOAS service that uses HAL, I would like to be able to make requests with the "application/hal+json" media type.

**Describe the solution you'd like**
I would like an additional option from the content type dropdown.

**Additional context**
I believe I have made the necessary code changes, but as the CONTRIBUTING.md file for this repo has no information, I'm not sure how to submit the PR.

### LINKED ISSUE #99: Content-Type revamping
I wanted to start a discussion around the future of Content-Type and what direction everyone thinks we should go in. @NBTX mentioned a great idea in #63 which I'll requote:

> I think we should make content-type a text field with 'command line completion' (autocomplete) for commonly used content types, rather than restricting to these two content types.

I personally love this idea. In addition to the auto-complete, a user could chose their own custom type, so that new types would not have to be manually implemented (#88). 

But a related issue I see is that Content-Type is a **header** and nothing more. POST/PUT requests don't require a Content-Type header to succeed, odd as it would be to omit one. Within the context of postwoman UI you could technically have a Content-Type in the header section while the Content-Type dropdown was selected. It wouldn't be apparent to the user which one was actually set.

So I propose a few changes. First is to move the headers above the body, making the hierarchy `Request > Headers > Request Body > Authentication > Parameters > Response > History`. Second, remove the Content-Type dropdown and use it within the Headers section. Third, auto expand the Headers sections when requests types that expect Content-Type is selected--when this happens, Content-Type can pre-populate with `application/json`. The user is then free to modify that header or remove it entirely.

Open for discussion--when a conclusion is met I'll make a separate issue detailing the plan

### PR DESCRIPTION
**Pull request by NBTX**
Test URL: https://nbtx.github.io/postwoman-vue/

---

postwoman-autocomplete-demo

This PR:
- adds a custom autocomplete searchbox (see GIF).
- automatically turns off the 'raw input' feature when a known content type is entered.
- allows for easily defining `knownContentTypes` and `validContentTypes` (see `index.vue`).
- renames `www-urlencoded` to its proper name `application/x-www-form-urlencoded`

- Resolves #88 
- Resolves #99

### CODE REVIEW

**Comment by liyasthomas** [comment]
Rebase and pull

**Comment by liyasthomas** [comment]
Had conflicts with binding query parameters and URL binding. Had to revert. Fix in your repo and pull again.

**Comment by NBTX** [comment]
Crap, I did try it after I merged it. Do you know what went wrong?

**Comment by liyasthomas** [comment]
Screenshot_20190901-072705_Chrome
This is from your repo. Most prolly #118  caused this.

**Comment by yubathom** [comment]
Sorry about that. I can review it if you want..

**Comment by liyasthomas** [comment]
Yeah sure. Please review.

**Comment by NBTX** [comment]
Ah! I think I worked out what the issue was. I had a commit to stringify request data for POST, etc. but presumably you did a GET or a request without a body.
I'll just fix that and submit another PR.

**Comment by liyasthomas** [comment]
It was `GET` :smile:

**Pull request merged**
